from . import help
from . import start
from . import Sotib_olish
from . import savatcha
from . import qidirish
from . import media
from . import tunukafon_qoshish
from . import maxsulotlar_button
from . import echo